In [9]:
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

data=pd.read_csv("income(1) (1).csv",na_values=[ " ?"])
data

age       JobType         EdType        maritalstatus  \
0       45       Private        HS-grad             Divorced   
1       24   Federal-gov        HS-grad        Never-married   
2       44       Private   Some-college   Married-civ-spouse   
3       27       Private            9th        Never-married   
4       20       Private   Some-college        Never-married   
...    ...           ...            ...                  ...   
31973   34     Local-gov        HS-grad        Never-married   
31974   34     Local-gov   Some-college        Never-married   
31975   23       Private   Some-college   Married-civ-spouse   
31976   42     Local-gov   Some-college   Married-civ-spouse   
31977   29       Private      Bachelors        Never-married   

             occupation     relationship    race   gender  capitalgain  \
0          Adm-clerical    Not-in-family   White   Female            0   
1          Armed-Forces        Own-child   White     Male            0   
2        Prof-specialty          Husband   White     Male            0   
3          Craft-repair   Other-relative   White     Male            0   
4                 Sales    Not-in-family   White     Male            0   
...                 ...              ...     ...      ...          ...   
31973   Farming-fishing    Not-in-family   Black     Male          594   
31974   Protective-serv    Not-in-family   White   Female            0   
31975      Adm-clerical          Husband   White     Male            0   
31976      Adm-clerical             Wife   White   Female            0   
31977    Prof-specialty    Not-in-family   White     Male            0   

       capitalloss  hoursperweek   nativecountry  \
0                0            28   United-States   
1                0            40   United-States   
2                0            40   United-States   
3                0            40          Mexico   
4                0            35   United-States   
...            ...           ...             ...   
31973            0            60   United-States   
31974            0            40   United-States   
31975            0            40   United-States   
31976            0            40   United-States   
31977            0            40   United-States   

                             SalStat  
0       less than or equal to 50,000  
1       less than or equal to 50,000  
2                greater than 50,000  
3       less than or equal to 50,000  
4       less than or equal to 50,000  
...                              ...  
31973   less than or equal to 50,000  
31974   less than or equal to 50,000  
31975   less than or equal to 50,000  
31976   less than or equal to 50,000  
31977   less than or equal to 50,000  

[31978 rows x 13 columns]

In [10]:
data.isnull().sum()

age                 0
JobType          1809
EdType              0
maritalstatus       0
occupation       1816
relationship        0
race                0
gender              0
capitalgain         0
capitalloss         0
hoursperweek        0
nativecountry       0
SalStat             0
dtype: int64

In [11]:
missing=data[data.isnull().any(axis=1)]
missing

age JobType         EdType        maritalstatus occupation  \
8       17     NaN           11th        Never-married        NaN   
17      32     NaN   Some-college   Married-civ-spouse        NaN   
29      22     NaN   Some-college        Never-married        NaN   
42      52     NaN           12th        Never-married        NaN   
44      63     NaN        1st-4th   Married-civ-spouse        NaN   
...    ...     ...            ...                  ...        ...   
31892   59     NaN      Bachelors   Married-civ-spouse        NaN   
31934   20     NaN        HS-grad        Never-married        NaN   
31945   28     NaN   Some-college   Married-civ-spouse        NaN   
31967   80     NaN        HS-grad              Widowed        NaN   
31968   17     NaN           11th        Never-married        NaN   

          relationship    race   gender  capitalgain  capitalloss  \
8            Own-child   White   Female            0            0   
17             Husband   White     Male            0            0   
29           Own-child   White     Male            0            0   
42      Other-relative   Black     Male          594            0   
44             Husband   White     Male            0            0   
...                ...     ...      ...          ...          ...   
31892          Husband   White     Male            0            0   
31934   Other-relative   White   Female            0            0   
31945             Wife   White   Female            0         1887   
31967    Not-in-family   White     Male            0            0   
31968        Own-child   White     Male            0            0   

       hoursperweek   nativecountry                        SalStat  
8                 5   United-States   less than or equal to 50,000  
17               40   United-States   less than or equal to 50,000  
29               40   United-States   less than or equal to 50,000  
42               40   United-States   less than or equal to 50,000  
44               35   United-States   less than or equal to 50,000  
...             ...             ...                            ...  
31892            40   United-States            greater than 50,000  
31934            35   United-States   less than or equal to 50,000  
31945            40   United-States            greater than 50,000  
31967            24   United-States   less than or equal to 50,000  
31968            40   United-States   less than or equal to 50,000  

[1816 rows x 13 columns]

In [12]:
data2=data.dropna(axis=0)
data2

age       JobType         EdType        maritalstatus  \
0       45       Private        HS-grad             Divorced   
1       24   Federal-gov        HS-grad        Never-married   
2       44       Private   Some-college   Married-civ-spouse   
3       27       Private            9th        Never-married   
4       20       Private   Some-college        Never-married   
...    ...           ...            ...                  ...   
31973   34     Local-gov        HS-grad        Never-married   
31974   34     Local-gov   Some-college        Never-married   
31975   23       Private   Some-college   Married-civ-spouse   
31976   42     Local-gov   Some-college   Married-civ-spouse   
31977   29       Private      Bachelors        Never-married   

             occupation     relationship    race   gender  capitalgain  \
0          Adm-clerical    Not-in-family   White   Female            0   
1          Armed-Forces        Own-child   White     Male            0   
2        Prof-specialty          Husband   White     Male            0   
3          Craft-repair   Other-relative   White     Male            0   
4                 Sales    Not-in-family   White     Male            0   
...                 ...              ...     ...      ...          ...   
31973   Farming-fishing    Not-in-family   Black     Male          594   
31974   Protective-serv    Not-in-family   White   Female            0   
31975      Adm-clerical          Husband   White     Male            0   
31976      Adm-clerical             Wife   White   Female            0   
31977    Prof-specialty    Not-in-family   White     Male            0   

       capitalloss  hoursperweek   nativecountry  \
0                0            28   United-States   
1                0            40   United-States   
2                0            40   United-States   
3                0            40          Mexico   
4                0            35   United-States   
...            ...           ...             ...   
31973            0            60   United-States   
31974            0            40   United-States   
31975            0            40   United-States   
31976            0            40   United-States   
31977            0            40   United-States   

                             SalStat  
0       less than or equal to 50,000  
1       less than or equal to 50,000  
2                greater than 50,000  
3       less than or equal to 50,000  
4       less than or equal to 50,000  
...                              ...  
31973   less than or equal to 50,000  
31974   less than or equal to 50,000  
31975   less than or equal to 50,000  
31976   less than or equal to 50,000  
31977   less than or equal to 50,000  

[30162 rows x 13 columns]

In [13]:
sal=data["SalStat"]

data2["SalStat"]=data["SalStat"].map({' less than or equal to 50,000':0,' greater than 50,000':1})
print(data2['SalStat'])

0        0
1        0
2        1
3        0
4        0
        ..
31973    0
31974    0
31975    0
31976    0
31977    0
Name: SalStat, Length: 30162, dtype: int64


C:\Users\SEC\AppData\Local\Temp\ipykernel_5552\3180796514.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["SalStat"]=data["SalStat"].map({' less than or equal to 50,000':0,' greater than 50,000':1})


In [14]:
sal2=data2['SalStat']

dfs=pd.concat([sal,sal2],axis=1)
dfs

SalStat  SalStat
0       less than or equal to 50,000      0.0
1       less than or equal to 50,000      0.0
2                greater than 50,000      1.0
3       less than or equal to 50,000      0.0
4       less than or equal to 50,000      0.0
...                              ...      ...
31973   less than or equal to 50,000      0.0
31974   less than or equal to 50,000      0.0
31975   less than or equal to 50,000      0.0
31976   less than or equal to 50,000      0.0
31977   less than or equal to 50,000      0.0

[31978 rows x 2 columns]

In [15]:
data2

age       JobType         EdType        maritalstatus  \
0       45       Private        HS-grad             Divorced   
1       24   Federal-gov        HS-grad        Never-married   
2       44       Private   Some-college   Married-civ-spouse   
3       27       Private            9th        Never-married   
4       20       Private   Some-college        Never-married   
...    ...           ...            ...                  ...   
31973   34     Local-gov        HS-grad        Never-married   
31974   34     Local-gov   Some-college        Never-married   
31975   23       Private   Some-college   Married-civ-spouse   
31976   42     Local-gov   Some-college   Married-civ-spouse   
31977   29       Private      Bachelors        Never-married   

             occupation     relationship    race   gender  capitalgain  \
0          Adm-clerical    Not-in-family   White   Female            0   
1          Armed-Forces        Own-child   White     Male            0   
2        Prof-specialty          Husband   White     Male            0   
3          Craft-repair   Other-relative   White     Male            0   
4                 Sales    Not-in-family   White     Male            0   
...                 ...              ...     ...      ...          ...   
31973   Farming-fishing    Not-in-family   Black     Male          594   
31974   Protective-serv    Not-in-family   White   Female            0   
31975      Adm-clerical          Husband   White     Male            0   
31976      Adm-clerical             Wife   White   Female            0   
31977    Prof-specialty    Not-in-family   White     Male            0   

       capitalloss  hoursperweek   nativecountry  SalStat  
0                0            28   United-States        0  
1                0            40   United-States        0  
2                0            40   United-States        1  
3                0            40          Mexico        0  
4                0            35   United-States        0  
...            ...           ...             ...      ...  
31973            0            60   United-States        0  
31974            0            40   United-States        0  
31975            0            40   United-States        0  
31976            0            40   United-States        0  
31977            0            40   United-States        0  

[30162 rows x 13 columns]

In [16]:
new_data=pd.get_dummies(data2, drop_first=True)
new_data

age  capitalgain  capitalloss  hoursperweek  SalStat  \
0       45            0            0            28        0   
1       24            0            0            40        0   
2       44            0            0            40        1   
3       27            0            0            40        0   
4       20            0            0            35        0   
...    ...          ...          ...           ...      ...   
31973   34          594            0            60        0   
31974   34            0            0            40        0   
31975   23            0            0            40        0   
31976   42            0            0            40        0   
31977   29            0            0            40        0   

       JobType_ Local-gov  JobType_ Private  JobType_ Self-emp-inc  \
0                       0                 1                      0   
1                       0                 0                      0   
2                       0                 1                      0   
3                       0                 1                      0   
4                       0                 1                      0   
...                   ...               ...                    ...   
31973                   1                 0                      0   
31974                   1                 0                      0   
31975                   0                 1                      0   
31976                   1                 0                      0   
31977                   0                 1                      0   

       JobType_ Self-emp-not-inc  JobType_ State-gov  ...  \
0                              0                   0  ...   
1                              0                   0  ...   
2                              0                   0  ...   
3                              0                   0  ...   
4                              0                   0  ...   
...                          ...                 ...  ...   
31973                          0                   0  ...   
31974                          0                   0  ...   
31975                          0                   0  ...   
31976                          0                   0  ...   
31977                          0                   0  ...   

       nativecountry_ Portugal  nativecountry_ Puerto-Rico  \
0                            0                           0   
1                            0                           0   
2                            0                           0   
3                            0                           0   
4                            0                           0   
...                        ...                         ...   
31973                        0                           0   
31974                        0                           0   
31975                        0                           0   
31976                        0                           0   
31977                        0                           0   

       nativecountry_ Scotland  nativecountry_ South  nativecountry_ Taiwan  \
0                            0                     0                      0   
1                            0                     0                      0   
2                            0                     0                      0   
3                            0                     0                      0   
4                            0                     0                      0   
...                        ...                   ...                    ...   
31973                        0                     0                      0   
31974                        0                     0                      0   
31975                        0                     0                      0   
31976                        0                     0                      0   
31977                        0                     0          

In [17]:
columns_list=list(new_data.columns)
print(columns_list)

['age', 'capitalgain', 'capitalloss', 'hoursperweek', 'SalStat', 'JobType_ Local-gov', 'JobType_ Private', 'JobType_ Self-emp-inc', 'JobType_ Self-emp-not-inc', 'JobType_ State-gov', 'JobType_ Without-pay', 'EdType_ 11th', 'EdType_ 12th', 'EdType_ 1st-4th', 'EdType_ 5th-6th', 'EdType_ 7th-8th', 'EdType_ 9th', 'EdType_ Assoc-acdm', 'EdType_ Assoc-voc', 'EdType_ Bachelors', 'EdType_ Doctorate', 'EdType_ HS-grad', 'EdType_ Masters', 'EdType_ Preschool', 'EdType_ Prof-school', 'EdType_ Some-college', 'maritalstatus_ Married-AF-spouse', 'maritalstatus_ Married-civ-spouse', 'maritalstatus_ Married-spouse-absent', 'maritalstatus_ Never-married', 'maritalstatus_ Separated', 'maritalstatus_ Widowed', 'occupation_ Armed-Forces', 'occupation_ Craft-repair', 'occupation_ Exec-managerial', 'occupation_ Farming-fishing', 'occupation_ Handlers-cleaners', 'occupation_ Machine-op-inspct', 'occupation_ Other-service', 'occupation_ Priv-house-serv', 'occupation_ Prof-specialty', 'occupation_ Protective-s

In [18]:
features=list(set(columns_list)-set(['SalStat']))
print(features)

['hoursperweek', 'nativecountry_ Canada', 'nativecountry_ Poland', 'EdType_ 1st-4th', 'occupation_ Sales', 'maritalstatus_ Married-spouse-absent', 'nativecountry_ Cuba', 'EdType_ Prof-school', 'nativecountry_ Japan', 'JobType_ Self-emp-inc', 'EdType_ 7th-8th', 'EdType_ Doctorate', 'race_ Asian-Pac-Islander', 'nativecountry_ Greece', 'nativecountry_ Portugal', 'EdType_ 9th', 'nativecountry_ Columbia', 'nativecountry_ Guatemala', 'EdType_ Some-college', 'occupation_ Protective-serv', 'EdType_ 5th-6th', 'relationship_ Unmarried', 'race_ Black', 'nativecountry_ United-States', 'nativecountry_ England', 'occupation_ Exec-managerial', 'nativecountry_ Jamaica', 'EdType_ 11th', 'nativecountry_ Honduras', 'nativecountry_ Mexico', 'nativecountry_ Laos', 'relationship_ Wife', 'nativecountry_ Dominican-Republic', 'JobType_ Self-emp-not-inc', 'nativecountry_ France', 'relationship_ Not-in-family', 'nativecountry_ Vietnam', 'nativecountry_ Ecuador', 'nativecountry_ Germany', 'nativecountry_ Iran', '

In [19]:
y=new_data['SalStat'].values
print(y)

[0 0 1 ... 0 0 0]


In [20]:
x=new_data[features].values
print(x)

[[28  0  0 ...  0  0  0]
 [40  0  0 ...  0  0  0]
 [40  0  0 ...  0  0  0]
 ...
 [40  0  0 ...  0  0  0]
 [40  0  0 ...  0  0  0]
 [40  0  0 ...  1  0  0]]


In [21]:
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.3,random_state=0)

KNN_classifier=KNeighborsClassifier(n_neighbors = 5)

KNN_classifier.fit(train_x,train_y)

KNeighborsClassifier()

In [22]:
prediction=KNN_classifier.predict(test_x)

confusionMatrix=confusion_matrix(test_y, prediction)
print(confusionMatrix)

[[6173  650]
 [ 843 1383]]


In [23]:
accuracy_score=accuracy_score(test_y,prediction)
print(accuracy_score)

0.8350093933031274


In [24]:
print("Misclassified Samples : %d" % (test_y !=prediction).sum())

Misclassified Samples : 1493


In [25]:

import pandas as pd
from sklearn.feature_selection import SelectKBest, mutual_info_classif, f_classif
data={
    'Feature1': [1,2,3,4,5],
    'Feature2': ['A','B','C','A','B'],
    'Feature3': [0,1,1,0,1],
    'Target'  : [0,1,1,0,1]
}

df=pd.DataFrame(data)
x=df[['Feature1','Feature3']]
y=df[['Target']]

selector=SelectKBest(score_func=mutual_info_classif,k=1)
x_new=selector.fit_transform(x,y)

selected_feature_indices=selector.get_support(indices=True)

selected_features=x.columns[selected_feature_indices]
print("Selected Features:")
print(selected_features)

Selected Features:
Index(['Feature3'], dtype='object')


c:\Users\SEC\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [26]:

import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency

import seaborn as sns
tips=sns.load_dataset('tips')
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [27]:

tips.time.unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [28]:

contingency_table=pd.crosstab(tips['sex'],tips['time'])
print(contingency_table)

time    Lunch  Dinner
sex                  
Male       33     124
Female     35      52


In [29]:

chi2,p,_,_=chi2_contingency(contingency_table)
print(f"Chi-Square Statistics: {chi2}")
print(f"P-Value: {p}")

Chi-Square Statistics: 9.343808982970623
P-Value: 0.002237400118075248
